# Los archivos docker-compose.yml son versionados, lo que significa que es muy importante indicar la versión de las instrucciones que queremos darle.
#version: "3.3"

# Servidor nginx
services:
  web:
    # versión
    image: nginx:latest
    # Puerto 8080 
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    networks:
      - multi-host-network

  mysql:
    image: mysql:8.0.28
    container_name: mysql8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass # Asegúrate de que esta contraseña esté especificada
      MYSQL_ALLOW_EMPTY_PASSWORD: "true" # Cambia a false si estás usando una contraseña
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init-scripts:/docker-entrypoint-initdb.d  # Mount the init scripts directory
      # Note: /docker-entrypoint-initdb.d is the path inside the container where scripts are executed on startup
    networks:
      - multi-host-network


  # Configuración de php-fpm
  php-fpm:
    image: php:8.2-fpm
    build:
      context: .
      dockerfile: Dockerfile  # Asegúrate de que apunte al Dockerfile correcto
    volumes:
      - ./srs:/var/www/html
    networks:
      - multi-host-network

volumes:
  mysql_data:
    driver: local

networks:
  multi-host-network:
    external: true

